#ifndef PUBLIC_CONFIG_H
#define PUBLIC_CONFIG_H

#define CONFIG_BOOT_PORT 4444
#define CONFIG_SERVER_PORT 5555
#define CONFIG_CLIENT_PORT 6666
#define CONFIG_RELAY_HOST "robin"

#define CONFIG_RELAY_PASSWORD "123456"

#define CONFIG_BOOTLOADER_IPADDR_OFFSET 5

#endif
